name: C++ CI

on:
  push:
    paths:
      - '**' # Запускать при добавлении любых новых файлов

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Сборка
        run: g++ -o circle_area circle_area.cpp
        
      - name: Запуск тестов
        run: ./circle_area
